FROM snarlysodboxer/hambone:v1.15.0 as hambone

FROM golang:1.13.5-stretch
ENV CGO_ENABLED=0 GOOS=linux
RUN go get github.com/githubnemo/CompileDaemon
COPY --from=hambone /usr/local/bin/hambone /usr/local/bin/hambone
COPY --from=hambone /usr/local/bin/kustomize /usr/local/bin/kustomize
COPY --from=hambone /usr/local/bin/kubectl /usr/local/bin/kubectl

