version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd:latest
    restart: always
    entrypoint:
      - /usr/local/bin/etcd
    command:
      - --data-dir=/etcd-data
      - --name=node1
      - --initial-advertise-peer-urls=http://127.0.0.1:2380
      - --listen-peer-urls=http://127.0.0.1:2380
      - --advertise-client-urls=http://127.0.0.1:2379
      - --listen-client-urls=http://127.0.0.1:2379
      - --initial-cluster=node1=http://127.0.0.1:2380
    volumes:
      - data-volume:/etcd-data
    network_mode: host

  watcher:
    image: snarlysodboxer/hambone:v1.7.3
    restart: always
    entrypoint:
      - hambone
    command:
      - --listen_address
      - "127.0.0.1:50051"
      - --state_store
      - etcd
      - -etcd_endpoints
      - "http://127.0.0.1:2379"
    volumes:
      - ./:/hambone
    network_mode: host # to be able to reach minikube

volumes:
  data-volume:
